/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddOutreachImport } from './routes/add-outreach'
import { Route as IndexImport } from './routes/index'
import { Route as TripsNewImport } from './routes/trips.new'
import { Route as TripsTripIdImport } from './routes/trips.$tripId'
import { Route as TripsTripIdSummaryImport } from './routes/trips.$tripId.summary'
import { Route as TripsTripIdScheduleImport } from './routes/trips.$tripId.schedule'

// Create/Update Routes

const AddOutreachRoute = AddOutreachImport.update({
  id: '/add-outreach',
  path: '/add-outreach',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TripsNewRoute = TripsNewImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRoute,
} as any)

const TripsTripIdRoute = TripsTripIdImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRoute,
} as any)

const TripsTripIdSummaryRoute = TripsTripIdSummaryImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => TripsTripIdRoute,
} as any)

const TripsTripIdScheduleRoute = TripsTripIdScheduleImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TripsTripIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-outreach': {
      id: '/add-outreach'
      path: '/add-outreach'
      fullPath: '/add-outreach'
      preLoaderRoute: typeof AddOutreachImport
      parentRoute: typeof rootRoute
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdImport
      parentRoute: typeof rootRoute
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewImport
      parentRoute: typeof rootRoute
    }
    '/trips/$tripId/schedule': {
      id: '/trips/$tripId/schedule'
      path: '/schedule'
      fullPath: '/trips/$tripId/schedule'
      preLoaderRoute: typeof TripsTripIdScheduleImport
      parentRoute: typeof TripsTripIdImport
    }
    '/trips/$tripId/summary': {
      id: '/trips/$tripId/summary'
      path: '/summary'
      fullPath: '/trips/$tripId/summary'
      preLoaderRoute: typeof TripsTripIdSummaryImport
      parentRoute: typeof TripsTripIdImport
    }
  }
}

// Create and export the route tree

interface TripsTripIdRouteChildren {
  TripsTripIdScheduleRoute: typeof TripsTripIdScheduleRoute
  TripsTripIdSummaryRoute: typeof TripsTripIdSummaryRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdScheduleRoute: TripsTripIdScheduleRoute,
  TripsTripIdSummaryRoute: TripsTripIdSummaryRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-outreach': typeof AddOutreachRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/schedule': typeof TripsTripIdScheduleRoute
  '/trips/$tripId/summary': typeof TripsTripIdSummaryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-outreach': typeof AddOutreachRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/schedule': typeof TripsTripIdScheduleRoute
  '/trips/$tripId/summary': typeof TripsTripIdSummaryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add-outreach': typeof AddOutreachRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/trips/new': typeof TripsNewRoute
  '/trips/$tripId/schedule': typeof TripsTripIdScheduleRoute
  '/trips/$tripId/summary': typeof TripsTripIdSummaryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-outreach'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/schedule'
    | '/trips/$tripId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-outreach'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/schedule'
    | '/trips/$tripId/summary'
  id:
    | '__root__'
    | '/'
    | '/add-outreach'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips/$tripId/schedule'
    | '/trips/$tripId/summary'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddOutreachRoute: typeof AddOutreachRoute
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  TripsNewRoute: typeof TripsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddOutreachRoute: AddOutreachRoute,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  TripsNewRoute: TripsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-outreach",
        "/trips/$tripId",
        "/trips/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-outreach": {
      "filePath": "add-outreach.tsx"
    },
    "/trips/$tripId": {
      "filePath": "trips.$tripId.tsx",
      "children": [
        "/trips/$tripId/schedule",
        "/trips/$tripId/summary"
      ]
    },
    "/trips/new": {
      "filePath": "trips.new.tsx"
    },
    "/trips/$tripId/schedule": {
      "filePath": "trips.$tripId.schedule.tsx",
      "parent": "/trips/$tripId"
    },
    "/trips/$tripId/summary": {
      "filePath": "trips.$tripId.summary.tsx",
      "parent": "/trips/$tripId"
    }
  }
}
ROUTE_MANIFEST_END */
